spring:
  application:
    name: reporting-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/predicador}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: default

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: health,info

whatsapp:
  api-version: "v21.0"
  base-url: "https://graph.facebook.com"
  phone-number-id: ${WHATSAPP_PHONE_ID:}
  access-token: ${WHATSAPP_ACCESS_TOKEN:}
  template-name: ${WHATSAPP_TEMPLATE:}
  language-code: ${WHATSAPP_LANG:es_CL}
  destination-number: ${WHATSAPP_DESTINATION:}
